version: '3.8'

services:
  postgres-db:
    image: postgres:15-alpine
    container_name: trucking_postgres
    environment:
      POSTGRES_USER: smartdepo
      POSTGRES_PASSWORD: smartdepo
      POSTGRES_DB: trucking_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  minio-storage:
    image: minio/minio
    container_name: trucking_minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: smartdepo
      MINIO_ROOT_PASSWORD: smartdepo
    volumes:
      - minio_data:/data
    command: server /data --address ":9000" --console-address ":9001"
    restart: always

volumes:
  postgres_data:
  minio_data:
